# Generated by Django 5.1.7 on 2025-07-07 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0003_alter_frame_options_alter_lenstype_options_and_more'),
        ('shops', '0004_delete_shopinventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(default=0, help_text='Total quantity received from distributor')),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Total quantity sold to customers')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, help_text='Cost per unit shop pays to distributor', max_digits=10)),
                ('last_restocked', models.DateTimeField(auto_now=True, help_text='Last time inventory was restocked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.frame')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Inventory',
                'verbose_name_plural': 'Shop Inventories',
                'unique_together': {('shop', 'frame')},
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('STOCK_IN', 'Stock In'), ('SALE', 'Sale'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('shop_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.shopinventory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month (YYYY-MM-01)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total revenue from sales', max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Total cost of goods sold', max_digits=12)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, help_text='Total profit (revenue - cost)', max_digits=12)),
                ('amount_to_pay_distributor', models.DecimalField(decimal_places=2, default=0, help_text='Amount owed to distributor', max_digits=12)),
                ('units_sold', models.PositiveIntegerField(default=0, help_text='Total units sold this month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Financial Summary',
                'verbose_name_plural': 'Shop Financial Summaries',
                'ordering': ['-month', 'shop'],
                'unique_together': {('shop', 'month')},
            },
        ),
    ]
