# Generated by Django 5.1.7 on 2025-07-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_shopinventory_inventorytransaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
