# Generated by Django 5.1.7 on 2025-07-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Shop contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='shop',
            name='owner_name',
            field=models.CharField(blank=True, default='', help_text="Shop owner's full name", max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Shop contact phone', max_length=20),
        ),
    ]
