# Generated by Django 5.1.7 on 2025-07-07 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_frame_options_alter_lenstype_options_and_more'),
        ('shops', '0002_shop_email_shop_owner_name_shop_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stock', models.PositiveIntegerField(default=0, help_text='Total stock received for this frame')),
                ('sold_count', models.PositiveIntegerField(default=0, help_text='Number of items sold')),
                ('remaining_count', models.PositiveIntegerField(default=0, help_text='Number of items remaining in stock')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.frame')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='shops.shop')),
            ],
            options={
                'verbose_name': 'Shop Inventory',
                'verbose_name_plural': 'Shop Inventories',
                'unique_together': {('shop', 'frame')},
            },
        ),
    ]
