# Generated by Django 5.1.7 on 2025-07-07 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_shopinventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopInventory',
        ),
    ]
