# Generated by Django 5.2.4 on 2025-07-07 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='inventory.inventoryitem')),
                ('lens_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.lenstype')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shops.shop')),
            ],
        ),
    ]
