# Generated by Django 5.1.7 on 2025-07-07 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
        ('shops', '0002_shop_email_shop_owner_name_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shops.shop'),
        ),
    ]
