# Generated by Django 5.1.7 on 2025-07-07 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('sales', '0003_alter_sale_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='inventory_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem'),
        ),
    ]
