# Generated by Django 5.1.7 on 2025-07-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='frame',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('brown', 'Brown'), ('gold', 'Gold'), ('silver', 'Silver'), ('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('transparent', 'Transparent'), ('tortoise', 'Tortoise'), ('grey', 'Grey')], default='black', max_length=50),
        ),
        migrations.AddField(
            model_name='frame',
            name='frame_type',
            field=models.CharField(choices=[('aviator', 'Aviator'), ('cat_eye', 'Cat-Eye'), ('rectangle', 'Rectangle'), ('round', 'Round'), ('square', 'Square')], default='rectangle', max_length=50),
        ),
        migrations.AddField(
            model_name='frame',
            name='material',
            field=models.CharField(choices=[('acetate', 'Acetate'), ('aluminum', 'Aluminum'), ('bamboo', 'Bamboo'), ('chrome', 'Chrome'), ('metal', 'Metal'), ('steel', 'Steel'), ('titanium', 'Titanium'), ('wood', 'Wood')], default='metal', max_length=50),
        ),
    ]
