# Generated by Django 5.1.7 on 2025-07-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_frame_brand_frame_color_frame_frame_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frame',
            options={'ordering': ['brand', 'name'], 'verbose_name': 'Frame', 'verbose_name_plural': 'Frames'},
        ),
        migrations.AlterModelOptions(
            name='lenstype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='lenstype',
            name='price',
        ),
        migrations.AddField(
            model_name='lenstype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lenstype',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='frame',
            name='brand',
            field=models.CharField(help_text='Frame brand/manufacturer', max_length=100),
        ),
        migrations.AlterField(
            model_name='frame',
            name='color',
            field=models.CharField(help_text='Frame color', max_length=50),
        ),
        migrations.AlterField(
            model_name='frame',
            name='frame_type',
            field=models.CharField(help_text='Type of frame (e.g., aviator, round, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='frame',
            name='material',
            field=models.CharField(help_text='Frame material', max_length=50),
        ),
        migrations.AlterField(
            model_name='frame',
            name='name',
            field=models.CharField(help_text='Frame model name', max_length=200),
        ),
        migrations.AlterField(
            model_name='frame',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Frame price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='frame',
            name='product_id',
            field=models.CharField(help_text='Unique product identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lenstype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
