# Generated by Django 5.1.7 on 2025-07-08 23:49

from django.db import migrations

def update_lens_prices(apps, schema_editor):
    """
    Update the price_modifier for existing LensType objects.
    """
    LensType = apps.get_model('products', 'LensType')
    
    lens_prices = {
        'Regular': 30.00,
        'Premium': 50.00,
        'Pro': 100.00,
    }
    
    for name, price in lens_prices.items():
        LensType.objects.update_or_create(
            name=name,
            defaults={'price_modifier': price}
        )

def revert_lens_prices(apps, schema_editor):
    """
    This is a one-way data migration. Reverting is not strictly necessary,
    but we can choose to set prices back to a default if needed.
    For this use case, we will not revert the prices.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_frame_options_alter_lenstype_options_and_more'),
    ]

    operations = [
        migrations.RunPython(update_lens_prices, revert_lens_prices),
    ]
